# 服务端口
server:
  port: 8301
# 服务名
spring:
  application:
    name: service-vod
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/glkt_vod?characterEncoding=utf-8
    username: root
    password: root
  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 上传大小
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml
# 腾讯运对象存储COS
tencent:
  cos:
    file:
      region: ap-beijing
      secretid: AKIDjIpIYdSNL8h48JUyN5pQmuocN3V1IPQI
      secretkey: 8CHF24PcfUSL5cz73oNjDc6cAkLo6C5m
      bucketname: ggkt-atguigu-1319501190